### ISSUE TITLE
Allow customization of proxy logs

### ISSUE THREAD

**Issue by dad264** [banzaicloud/istio-operator#293]
**Is your feature request related to a problem? Please describe.**
In our shop, we like to write all of our logs out in JSON format. From what I can tell, it's not currently a parameter as seen here: 

https://github.com/banzaicloud/istio-operator/blob/master/pkg/resources/common/configmap.go#L49

**Describe the solution you'd like to see**
I'd like to be able to set proxy.accessLogEncoding and proxy.accessLogFormat as mentioned here: https://istio.io/docs/tasks/telemetry/logs/access-log/#enable-envoy-s-access-logging

**Describe alternatives you've considered**
Configure our central logging system to "grok" the istio-proxy logs in their current/default format. 

**Additional context**
Thanks for all you do. This operator has been super useful!

**Comment by Laci21** [comment]
Hi @dad264,

Thank you for your kind words!

We will do our best to implement this feature in the next 2-3 weeks, but in around two weeks we will have a [Backyards](https://banzaicloud.com/blog/istio-the-easy-way/) release, until then we have limited capacity, so we cannot promise anything. If you need the feature sooner and you are up for it, we are more than happy to accept PRs. Otherwise, we will try to resolve this as soon as we can.

**Comment by Laci21** [comment]
We merged #298 to the `release-1.3` branch and will release a version tomorrow morning to support this feature with Istio 1.3. We will backport this feature to the `release-1.2` (Istio 1.2) branch as well soon.
