### ISSUE TITLE
Migration path from Istio installed by Istio methods and by the Istio Operator

### ISSUE THREAD

**Issue by inhabitech** [banzaicloud/istio-operator#311]
**Is your feature request related to a problem? Please describe.**
I want to start using Istio in my production environment. However, I want to explore usage of things like Kiali which are currently not supported by the operator.

**Describe the solution you'd like to see**
An easy to use upgrade path where I can switch from using a "standard Istio install" to using the operator.

Is this possible, or will I ultimately need to pick one way of installation and go that way unless I am willing to undergo a service disruption while I move from one method to the other?

**Comment by Laci21** [comment]
Hi,

If you have an Istio control plane running on your cluster, installed with Istio's official Helm charts, you should be able to simply install the Banzai Cloud Istio Operator on your cluster and then your Istio control plane will be managed by the operator from that point on.

To install the operator, you can check the [documented installation methods](https://github.com/banzaicloud/istio-operator#installation). It is basically as easy as deploying the operator itself and then creating an Istio Custom Resource for your needs.

If you set different configurations in your Istio CR compared to what you've used for your Helm install then the Istio control plane components (e.g. Pilot, Galley, etc.) will be reconciled automatically by the operator to use the new configurations. **The data plane (your applications) will not be affected at all so there will be no service disruption.**

In case you've already had Kiali installed on your cluster or you did not have it already installed, but you install it for yourself then it should work just fine with the operator as well.

The Istio Operator does not install and manage tools like Prometheus, Grafana, Jaeger or Kiali instead it enables to easily integrate and work with these components. However, we have a product called [Backyards](https://banzaicloud.com/blog/istio-the-easy-way/) which can help you install Prometheus, Grafana and Jaeger (besides Istio itself with the Istio operator) on your cluster, but instead of Kiali, it comes with its own UI for observability and besides that it is a feature rich management tool for your service mesh, is single- and multi-cluster compatible, and is possessed of a powerful CLI and GraphQL API.

The easiest way to get started with the operator and Backyards is by using the [Backyards CLI](https://github.com/banzaicloud/backyards-cli).

Let us know if this answered your question or get in touch with us in our [community Slack channel](https://slack.banzaicloud.io/), specifically the `#istio-operator` or `#backyards` channels if you have further questions.

**Comment by inhabitech** [comment]
Awesome. Sounds great, thanks!
