### ISSUE TITLE
Tracer can not be set to value "stackdriver"

### ISSUE THREAD

**Issue by Starefossen** [banzaicloud/istio-operator#336]
**Describe the bug**

With the current CRD definitions for v1.4 the `tracing.tracer` can only be set to the following enums 

https://github.com/banzaicloud/istio-operator/blob/8cf4c40cbe9ef567d8f272bb412ba5ed10923149/deploy/charts/istio-operator/templates/operator-istio-1.4-crd.yaml#L982-L986

**Steps to reproduce the issue:**

Deploy an istio with the following configuration:

```yaml
spec:
  tracing:
    enabled: true
    tracer: stackdriver
```

**Expected behavior**

According to the source code this should be supported by the operator?

**Screenshots**

**Additional context**
Add any other context about the problem like release numberm version, branch, etc.

Latest version of the operator and latest supported version of Istio (v1.4.0)

**Comment by Laci21** [comment]
Thanks for reporting this, @Starefossen!

Originally, when we added tracing support in the operator we did not have `stackdriver` support implemented, but since then we added the necessary logic to it to the code, so we might as well allow to use it now, it just needs to be tested.

I've just created a PR for this (#337), until it is merged you can test it on the `add-stackdriver` branch, if  you wish.
