### ISSUE TITLE
non root istio

### ISSUE THREAD

**Issue by jescarri** [banzaicloud/istio-operator#378]
**Is your feature request related to a problem? Please describe.**

When running istio with a CNI instead of sidecar for istio-proxy it's possible to run all the controlplane (with the exception of the CNI daemonset) and users workloads with non root privileges. 

**Describe the solution you'd like to see**
The ability to have a hardened PSP as the cluster default and user-workloads should be able to use this.

Control plane components and injected istio-proxies running as non root and with dropped capabilities.

**Describe alternatives you've considered**
Add a psp for cni components.
Add a psp that allows NodeAgent to use hostPath
Add a psp that allows the injected istio-proxies to use hostPath in RO mode to the specific sds path `/var/run/sds`
Change the controlplane/istio-proxy securityContexts to run as unprivileged users.
Change istio-proxy arguments to --configDir=/tmp

**Comment by Laci21** [comment]
Hi @jescarri,

Thank you for your feature request! This is definitely a useful security feature which we are working on to add.

First, we are identifying for each and every Istio component and proxy container the least privileges that are needed to be able to run them properly, then we are going to add these privileges to every container's security context and lastly, we are going to provide the most hardened PSP's which can be used for the Istio components.

We are planning to finish this soon in the upcoming weeks.

**Comment by jescarri** [comment]
@Laci21 ah! perfect, I was starting to get a list of all the required changes, as we have done some work already and have an istio install running as non root, using istioctl and then prepare for a PR, but you guys already working on it, so it's cool!

bellow is a draft of the listt:

`````
# PSPs adjustments
- Create PSP to allow host-path. for SDS and Istio Dataplane
- NodeAgent wants to run as r00t: message: container has runAsNonRoot and image will run as root
- IstioCni to create the psps for hostNetwork

- Gateway Service Traffic Policy.

Labeling seems posible for each of the components.


# PSPs

NodeAgent
---------

- hostPath -> /var/run/sds
- cap DropAll.
- SA istio-nodeagent-service-account

meshGateway
-----

- it Run as Root.
- hostPath /var/run/sds
- capDropAll
- hostPath -> /var/run/sds RO

Citadel
----

- It requires capDropAll
- it runs as root but missing a SecurityContext
````

Hope it helps, and I can test the new operator once you guys have something ready!.

**Comment by jescarri** [comment]
Hey guys, is there any work to get istio to run as non root done?

I wonder if the newest release of the operator has this feature.

Thanks!

**Comment by Laci21** [comment]
Hi @jescarri,

Sorry for getting back to you just now.

Well, the newest release kind of has this feature :)

You might know that in Istio 1.6 the legacy Istio control plane components (Pilot, Galley, Citadel, Sidecar Injector) were removed completely and there is a single istiod deployment instead of them. Also, part of the logic for SDS was moved to istiod and the NodeAgent component is not used anymore in 1.6. With these simplifications, there are fewer components (basically istiod and gateways) and it's easier to narrow the privileges of these containers.

- istiod runs as non root
- gateways can be run as non root by setting this flag to false: https://github.com/banzaicloud/istio-operator/blob/release-1.6/config/samples/istio_v1beta1_istio.yaml#L49 (and this for additional gateways: https://github.com/banzaicloud/istio-operator/blob/release-1.6/config/samples/istio_v1beta1_meshgateway.yaml#L16)

We haven't added a sample PSP for these components yet, which we might do as well.

**Comment by jescarri** [comment]
awesome! thanks I will give it a try in the upcoming days!

**Comment by Laci21** [comment]
@jescarri, we have made some adjustments to this in #444. You should be able to try it using Kustomize with the psp overlay described at the bottom of this README: https://github.com/banzaicloud/istio-operator/blob/release-1.6/config/README.md

This is just an example PSP setup, of course you can adjust them to your needs.

This security feature landed in docker image version `0.6.2`, helm chart version `0.0.51`.

**Comment by Laci21** [comment]
Here's the blog post on the subject, for further reference: https://banzaicloud.com/blog/istio-operator-psp/

**Comment by jescarri** [comment]
awesome thanks!
