### ISSUE TITLE
add an example for deploying Istio cluster with istio-operator

### ISSUE THREAD

**Issue by tanjunchen** [banzaicloud/istio-operator#429]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like to see**
A clear and concise description of what would you like to happen.

**Describe alternatives you've considered**

**Additional context**

**Comment by Laci21** [comment]
Have you seen the CR samples here? https://github.com/banzaicloud/istio-operator/tree/release-1.5/config/samples

There is an example in the readme as well: https://github.com/banzaicloud/istio-operator#installation

**Comment by tanjunchen** [comment]
@Laci21  Yes I have seen it. Thanks

**Comment by tanjunchen** [comment]
@Laci21  now i have some question about this istio-operator. could you help me?
1. the relationship  between istio-operator and [istio/istio/operator](https://github.com/istio/istio/tree/master/operator)
2. About the upgrade of sidecar with istio-operator. see https://github.com/banzaicloud/istio-operator/blob/release-1.5/docs/upgrade.md#istio-data-plane-upgrade.
3. I should modify which files if we want to  change the version of Istio Component .
4. for https://github.com/banzaicloud/istio-operator/blob/release-1.5/docs/upgrade.md#install-istio-152 , maybe we should use https not git .  can we use other ns , such as istio-operator not istio-system namaspace ? see  https://github.com/banzaicloud/istio-operator/blob/release-1.5/config/base/manager/namespace.yaml#L7.

**Comment by Laci21** [comment]
@tanjunchen, please see my answers below:

> @Laci21 now i have some question about this istio-operator. could you help me?
> 
> 1. the relationship  between istio-operator and [istio/istio/operator](https://github.com/istio/istio/tree/master/operator)

We [open-sourced](https://banzaicloud.com/blog/istio-operator/) this Banzai Cloud Istio operator in February, 2019 and it's been used in production by many companies since then. The other Istio operator by the Istio community was released much later and it is still not advised to be used in production in the newest Istio 1.6 release according to the [Istio docs](https://istio.io/docs/setup/install/standalone-operator/).

So, even though the basic purpose of the two operator are very similar, which is to install, upgrade and manage Istio meshes, they are two totally different implementations. In the Banzai Cloud Istio operator we have quite a few unique features like [managing multiple ingress/egress gateways](https://banzaicloud.com/blog/istio-multiple-gateways/), [automated and fine-tuned multi cluster management](https://banzaicloud.com/blog/backyards-multicluster-istio/) and so on. We and our customers rely on these features in our service mesh product on top of Istio, [Backyards](https://banzaicloud.com/products/backyards/), which uses the Banzai Cloud Istio operator.

> 2. About the upgrade of sidecar with istio-operator. see https://github.com/banzaicloud/istio-operator/blob/release-1.5/docs/upgrade.md#istio-data-plane-upgrade.

With the Banzai Cloud Istio Operator the [Istio control plane upgrade is automated](https://banzaicloud.com/blog/istio-control-plane-upgrade/). To upgrade the data plane you need to restart your pods e.g. with `kubectl rollout restart deployment your_deployment_name`.

> 3. I should modify which files if we want to  change the version of Istio Component .

The Istio Custom Resource describes the desired state of your Istio mesh, you should modify that resource. You can change image version for each component, e.g. you can change the Pilot image [here](https://github.com/banzaicloud/istio-operator/blob/release-1.5/config/samples/istio_v1beta1_istio.yaml#L30).

> 4. for https://github.com/banzaicloud/istio-operator/blob/release-1.5/docs/upgrade.md#install-istio-152 , maybe we should use https not git .  can we use other ns , such as istio-operator not istio-system namaspace ? see  https://github.com/banzaicloud/istio-operator/blob/release-1.5/config/base/manager/namespace.yaml#L7.

You can clone with HTTPS if you wish.
Installing to other namespace should be possible to do, but it does not work out-of-the box, needs some manual tweaks, it is not well tested and not something we recommend as of right now.

**Comment by tanjunchen** [comment]
@Laci21 
Thank you very much . I get it. Thanks again!

**Comment by tanjunchen** [comment]
@Laci21  for https://github.com/banzaicloud/istio-operator/blob/release-1.5/docs/upgrade.md#deploy-sample-bookinfo-application

Can I use NodePort?

**Comment by Laci21** [comment]
You can indeed determine if the service type of an ingress/egress gateway is ClusterIP, NodePort or LoadBalancer: https://github.com/banzaicloud/istio-operator/blob/b180a46a8ac3df339dfaf1b91b85a6719f6ea7cd/pkg/apis/istio/v1beta1/meshgateway_types.go#L43-L44

Regrading that specific example, the istio-ingressgateway service has LoadBalancer type so that it can be accessed from outside of the cluster, but you can define ingress gateways with NodePort type as well.

**Comment by tanjunchen** [comment]
I can't directly kubectl edit  istio-ingressgateway svc to make it to a NodePort type in my local cluster.
Must the above API types be redefined?

**Comment by Laci21** [comment]
You should edit the Istio Custom Resource: https://github.com/banzaicloud/istio-operator/blob/release-1.6/config/samples/istio_v1beta1_istio.yaml#L45

The operator will take care of the rest for you.
