### ISSUE TITLE
Make RollingUpdate strategy of Istio components configurable

### ISSUE THREAD

**Issue by Obirah** [banzaicloud/istio-operator#802]
**Is your feature request related to a problem? Please describe.**
The `Istio` CustomResource allows users to configure pod anti-affinity for the Istio components. In my case, I'm deploying an ingress gateway with three replicas into three different AWS availability zones by using pod anti-affinity.

Unfortunately, the Deployment of the ingress gateway has the value `maxUnavailable: 25%` in its rolling update strategy. This collides with my anti-affinity which would require a maxUnavailable value of at least 34% and leads to the rolling update being stuck because it is not allowed to terminate any old pods.

**Describe the solution you'd like to see**
I would like to have the option to at least configure the maxUnavailable value (if not the whole rolling update strategy) for each component in the `Istio` CustomResource. Something likes this:

```
spec:
  gateways:
    ingress:
      enabled: true
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 34%
          maxSurge: 25%
```

**Describe alternatives you've considered**
I'm currently using the [Resource Locker Operator](https://github.com/redhat-cop/resource-locker-operator) in order workaround the issue by creating a declarative, version-controlled patch for the Istio ingress gateway deployment that applies and locks the maxUnavailable value.

Another alternative would be deploying 6 replicas instead of 3, then 25% would work but on the other hand it would be a waste of computing resources.

**Additional context**
See [this article](https://medium.com/xmglobal/how-can-affinity-rules-break-your-kubernetes-rolling-updates-3055eb2d478c) for more insights on how affinity and rolling update strategy may collide.

**Comment by Laci21** [comment]
Hi @Obirah,

We have recently completely rewritten the Istio operator, which contains totally new APIs and backward incompatible changes to the versions before. You can find the new version on the [release-1.11](https://github.com/banzaicloud/istio-operator/tree/release-1.11) branch. (We are yet to add documentation to the new version, that's why it was not advertised yet.)

The new version has a CRD called `IstioMeshGateway`: https://github.com/banzaicloud/istio-operator/blob/release-1.11/api/v1alpha1/istiomeshgateway.proto#L56-L75 With this CR it is possible to create your own ingress/egress gateways as you'd like. In its spec there is a `deployment` field where you can specify a lot of options and the [DeploymentStrategy](https://github.com/banzaicloud/istio-operator/blob/release-1.11/api/v1alpha1/common.proto#L164) as well. There you can set the fields that you are looking for: https://github.com/banzaicloud/istio-operator/blob/release-1.11/api/v1alpha1/common.proto#L184-L198

We'll only support the new Istio operator version in the future, so I can only suggest to move to that. Feel free to reach out with questions (especially until the doc is not there for the new version).

**Comment by Obirah** [comment]
Hi @Laci21,

thank you so much for the quick response. As we use your operator within an operator of our own that provisions certain Istio components, we will have to refactor our operator in order to migrate.

We'll gladly do so soon-ish. For now, I will close this specific issue and we'll open new ones if we need support during the migration.
